name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'scripts/**'

env:
  DOTNET_VERSION: "8.0.x"

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore
        run: dotnet restore ./CabaVS.ExpenseTracker.sln
      
      - name: Build
        run: dotnet build ./CabaVS.ExpenseTracker.sln --configuration Release --no-restore
        
      - name: Architecture Tests
        run: dotnet test ./tests/CabaVS.ExpenseTracker.ArchitectureTests/CabaVS.ExpenseTracker.ArchitectureTests.csproj --configuration Release --no-restore --no-build
        
      - name: Unit Tests
        run: dotnet test ./tests/CabaVS.ExpenseTracker.UnitTests/CabaVS.ExpenseTracker.UnitTests.csproj --configuration Release --no-restore --no-build --collect:"XPlat Code Coverage"
        
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '**/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY